# Board
CONVERT_TO = liatris

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = azoteq_iqs5xx

# Features
ENCODER_ENABLE = no
MOUSEKEY_ENABLE = no
RGB_MATRIX_ENABLE = no

AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes
