#pragma once

#define AUTO_SHIFT_TIMEOUT 143
#define AUTO_SHIFT_REPEAT
#define NO_AUTO_SHIFT_SYMBOLS
#define NO_AUTO_SHIFT_NUMERIC
#define AUTO_SHIFT_NO_SETUP

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_INVERT_ON_SHIFT

#define TAPPING_TERM 170
#define PERMISSIVE_HOLD
